server:
  port: 7000
  servlet:
    context-path: /ad-search

spring:
  application:
    name: eureka-client-ad-search
  profiles:
    active: dev
  #    active: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"