server:
  port: 7002
  servlet:
    context-path: /ad-dump

spring:
  application:
    name: eureka-client-ad-dump
  profiles:
    active: dev
  #    active: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka